### PR TITLE
fix: increase Polygon gas limit

### PR DESCRIPTION
**Pull request by Rachel-Eichenberger**
So Large issues with polygon, not sure if this is the right way to go as it seems like the page (swap and pool) are looping highly in calls for quotes, this is causing huge errors in UI, long lists of RPC and gas errors see https://github.com/Uniswap/interface/issues/3718  and  https://github.com/Uniswap/interface/issues/3733  for reference 

Adding a gas over ride for the network, stops the errors, and possible network activity better due to not failing
¯\ (◉‿◉) /¯
not 100% if this is best way to go about this, so please let me know 

image
image

### CODE REVIEW

**Comment by Rachel-Eichenberger** [comment]
Not sure what's up with the Unit Tests, had a couple local things that accidently got pushed, but removed the bits. getting
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_3e7af9a1-881a-44af-9f4d-aea4e4e2ac6a/7333c17a-2e5a-41ee-8ec3-6553a4dd63ca.tar.gz. return code: 2.

**Comment by ivanmatiaspascual** [comment]
It seams work too with Arbitrum One

**Review by vm — APPROVED** [review]
this seems reasonable to me, we'll likely merge tomorrow once one other person takes a look

**Comment by Rachel-Eichenberger** [comment]
@vm 
So with recent updates, I'm getting an error in tests with the cypress test matrix,
not sure why, I did test on my comp, although these are calls, technically it does go over "max gas" although not sure if they have a fixed or variable max gas. 
also had an issue with last merge I did, not getting some crowdin download, giving my repo a fail in the job. Not sure why, but Not sure my repo is ok right now, but I would love second opinions 
image

**Comment by vm** [comment]
if you rebase one more time the tests will work, i fixed on main earlier today

**Comment by Rachel-Eichenberger** [comment]
@vm 
So I am new to this whole github arena, when I try to rebase, it says cant rebase onto itself
probably doing something wrong
image

**Comment by vm** [comment]
you can just merge main into your branch like you were doing before, don't worry about rebasing

**Comment by Rachel-Eichenberger** [comment]
@vm
Thank you so much, I've been messing with it for the past couple days, even kept trying to do another merge, but it just showed up again, and this time all passed
 :) , very much appreciated

**Comment by Rachel-Eichenberger** [comment]
Well not sure if it matters, but I am still getting the crowdin download issue
image

**Comment by vm** [comment]
don't worry about the crowd-in 👍

**Comment by vm** [comment]
I think this will only solve the issue if using the client-side router correct? As in you turned off the routing API.

**Comment by Rachel-Eichenberger** [comment]
It looks like it does, but tbh, I'm not 100% about the different paths it takes

**Pull request merged**
