### PR TITLE
fix: fixing price range filter passing as number

### PR DESCRIPTION
**Pull request by JackShort**
* app crashes when url is loaded with price range because it is passing in a number instead of a string causing it to crash

https://linear.app/uniswap/issue/WEB-2523/[safari]-blank-page-and-then-get-something-went-wrong-error-when-set

### CODE REVIEW

**Review by cbachmeier — APPROVED** [review]

**Review by just-toby — APPROVED** [review]
can we add a test that would catch this crash?

**Review by zzmp — CHANGES_REQUESTED** [review]
This should be caught by typechecking. Why is `maxPrice` _able_ to be anything other than a string? I think that's the root cause, and what should be fixed. This seems like a band-aid that may not prevent recurrence in the future.

> can we add a test that would catch this crash?

typechecking _should_ do this for us, as `parseEther` is typed to only accept a `string`.

**Comment by zzmp** [comment]
Can you also link the ticket or include a repro in the description, so that we can repro the original issue?

**Comment by JackShort** [comment]
> This should be caught by typechecking. Why is `maxPrice` _able_ to be anything other than a string? I think that's the root cause, and what should be fixed. This seems like a band-aid that may not prevent recurrence in the future.
> 
> > can we add a test that would catch this crash?
> 
> typechecking _should_ do this for us, as `parseEther` is typed to only accept a `string`.

Yeah i agree this is a bandaid solution that is because the underlying problem is a lot bigger - it has to do with the way the nft page encodes and decodes the url params. So this is definitely something we have to look at more, but the actual solution involves changing a lot of things involving the urlParams and how we handle them. And is a little more tedious and I just wanted to get this fix in so it we can patch staging and it doesn't crash prod

**Review by zzmp — APPROVED** [review]
That's fine, as long as you can ticket it so it doesn't get lost. Someone should audit the query param parsing to see why it is casting params to the wrong types.

**Comment by JackShort** [comment]
> That's fine, as long as you can ticket it so it doesn't get lost. Someone should audit the query param parsing to see why it is casting params to the wrong types.

yeah already pinged adrian about it. I am aware why this is happening there is a spot where we query for url params and we have convert to numbers set as true and then we set the state of collectionFilters based of a variable that is typed as any which overrides it at runtime to a number. but in order to change that we have to change a bunch of the way we handle urlParams

**Pull request merged**
