### PR TITLE
fix: No V2 factory address on this chain #3762

### PR DESCRIPTION
**Pull request by 0xbeny**
the issue is fixed by adding Supported Chain Ids
Added :
-POLYGON
-ARBITRUM_ONE
-OPTIMISM

### CODE REVIEW

**Comment by moodysalem** [comment]
there is no v2 on these networks, so the proper fix is to just handle it on the pages

**Comment by behnammohammadkhani** [comment]
you're right, so what is the approach here. do you mean disabling some components or showing alert, when changing network. 
please mention what exactly you want, i'm ready to fix

**Comment by moodysalem** [comment]
> you're right, so what is the approach here. do you mean disabling some components or showing alert, when changing network. please mention what exactly you want, i'm ready to fix

the proper fix would be, when connected to an unsupported network, show a message to that effect on the v2 pages

**Comment by vm** [comment]
https://github.com/Uniswap/interface/pull/3913 resolved in this pr

**Pull request closed without merging**
