### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by grabbou**
Fixes WEB-2552, as per https://github.com/Uniswap/interface/pull/5540

### CODE REVIEW

**Comment by grabbou** [comment]
My only concern with this PR is reduced visibility on what version we're running. I do wonder if it would make sense to annotate each commit sha with a version it refers to?

**Comment by zzmp** [comment]
> My only concern with this PR is reduced visibility on what version we're running. I do wonder if it would make sense to annotate each commit sha with a version it refers to?

I think this makes sense.

I also think if we're planning on moving to a `.github` repo for shared actions, we can deprioritize this so that _that_ can be used as a source of truth.

**Review by zzmp — COMMENTED** [review]
> My only concern with this PR is reduced visibility on what version we're running. I do wonder if it would make sense to annotate each commit sha with a version it refers to?

I think this makes sense.

I also think if we're planning on moving to a `.github` repo for shared actions, we can deprioritize this so that _that_ can be used as a source of truth.

**Comment by amrsag** [comment]
Un subscribed pls

**Comment by grabbou** [comment]
Let's revisit in the future once we wrap up shared GitHub actions template. While I generally agree in principle that pinning down action versions is a good action, I have mixed feelings about readability and maintenance of it in the form presented in this PR.

**Pull request closed without merging**
