### PR TITLE
fix: remove error popup when switching chains from URL param

### PR DESCRIPTION
**Pull request by just-toby**
## Description

Prevents an error popup from appearing when switching chains from the URL param

### Before

image

### After

no popup appears

### Reproducing the error

1.  navigate to https://app.uniswap.org/#/swap?chain=optimism when your wallet is not already set to optimism

### QA (ie manual testing)

- [x] manually tested and added an e2e test ensuring this URL param continues to work in the future

### Automated testing

- [x] Unit test
- [x] Integration/E2E test

### CODE REVIEW

**Comment by cbachmeier** [comment]
> navigate to https://app.uniswap.org/#/swap?chain=optimism when your wallet is not already set to optimism
I'm not getting this error on main app, is there a specific wallet I need to be connected with? I've tried MM, WC, and Uni

**Comment by JFrankfurt** [comment]
also unable to replicate the original error

**Comment by JFrankfurt** [comment]
on the preview link when I connect to the app, put my wallet on mainnet, close the tab, then direct nav to https://interface-git-fix-url-param-chainid-uniswap.vercel.app/#/swap?chain=optimism

I get
1. flash of optimism state (red background etc)
2. mainnet state

is this expected?

**Review by zzmp — APPROVED** [review]
lgtm, but you'll need to test using Polygon

**Comment by zzmp** [comment]
I was able to replicate by pasting the url in an already connected and open page. That way, the same SPA reacts to the new query param.

**Review by JFrankfurt — APPROVED** [review]

**Pull request merged**
