### PR TITLE
style: Add prettier organize imports plugin and run on all files

### PR DESCRIPTION
**Pull request by cmcewen**
Add a prettier plugin to organize imports - h/t @willpote

### CODE REVIEW

**Comment by zzmp** [comment]
Which files did you manually edit?

**Review by zzmp — APPROVED** [review]

**Comment by zzmp** [comment]
It seems like ESLint and prettier are fighting over formatting. Any idea why?

**Review by zzmp — CHANGES_REQUESTED** [review]
prettier and ESLint are fighting over formatting.
deployment failed.

sorry to double-comment, but I don't know how else to rescind approval.

**Comment by cmcewen** [comment]
no worries! @zzmp i just updated the plugin/prettier versions and it seems like it's fixed now

**Comment by cmcewen** [comment]
ugh nvm - will take another look tomorrow

**Comment by justindomingue** [comment]
> ugh nvm - will take another look tomorrow

did you delete `yarn.lock` locally at some point?

**Comment by moodysalem** [comment]
i merged a totally separate plugin to main and updated the workflow to use `pull_request` instead of `pull_request_target` because that seemed to not be helping at all with forks

**Pull request closed without merging**
