### PR TITLE
docs: Update PR template

### PR DESCRIPTION
**Pull request by yyip-dev**
## Description
Updating the PR template to standardize how PR descriptions are written. The purpose is to help contributors provide useful context to reviewers to understand the changes being made and how they're being tested.

- Moved PR Title convention to `README.md`
- Took inspiration from backend + mobile PR templates.

## Test Plan
n/a

### CODE REVIEW

**Comment by tinaszheng** [comment]
thoughts on also adding a section on screenshots/screen recordings? i've found that really helpful on the mobile team. here's their [template](https://github.com/Uniswap/mobile/blob/main/.github/PULL_REQUEST_TEMPLATE.md) for reference

**Comment by yyip-dev** [comment]
@tinaszheng oo i like that! updating

**Review by JFrankfurt — APPROVED** [review]
- consider a link out to the PR Title section in the readme
- consider removing the monitoring section of the template, as we don't currently implement any continuous monitoring other than sentry logs

**Comment by yyip-dev** [comment]
@JFrankfurt Good suggestions you made! Linked out to PR title conventions + agree we can add in monitoring when we have more applicable setup.

**Comment by grabbou** [comment]
Instead of shipping this as PR, would it be possible to do it as a design doc / proposal first? I think we should standardise this not just for this project, but for all the others too. We need a solid and well thought-out template and if there's already work happening for this project, I would like it to extend to other repositories too.

CC: @cmcewen

**Comment by yyip-dev** [comment]
@grabbou I think we should update the PR template asap to solve the problem of many PRs in the interface not having context or testing plan. I referenced https://github.com/Uniswap/data-api-graphql/blob/main/.github/pull_request_template.md and https://github.com/Uniswap/mobile/blob/main/.github/PULL_REQUEST_TEMPLATE.md which have been working well for those teams. Right now the PR template just tells people to put a keyword before PR titles.

A formal proposal seems overkill to me for a PR template. Maybe this is not as detailed and prescriptive as we want to move towards eventually, but it'll at least get people filling out and thinking about it when opening PRs. We can iterate on it easily if we want to add/edit anything. Also happy to add to all other web repos.

Happy to let you and @cmcewen take the lead on this. I'm fairly convinced this is worth merging in for now.

**Review by just-toby — APPROVED** [review]

**Review by cmcewen — APPROVED** [review]

**Pull request merged**
