### PR TITLE
fix: remove step indicators in sucess state

### PR DESCRIPTION
**Pull request by just-toby**
## Description

remove the step indicators in the success state

_Linear ticket:_ https://linear.app/uniswap/issue/WEB-2150/permit2-upon-success-remove-dot-indicators

### Before
|    Mobile    |   Desktop    |
| ------------ | ------------ |
| paste_before | image |

### After
|    Mobile    |   Desktop   |
| ------------ | ----------- |
| paste_after  | image |

### CODE REVIEW

**Comment by just-toby** [comment]
Current dependencies on/for this PR:
* main
  * **PR #6715** <a href="https://app.graphite.dev/github/pr/Uniswap/interface/6715" target="_blank">Graphite</a> 
    * **PR #6716** <a href="https://app.graphite.dev/github/pr/Uniswap/interface/6716" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Uniswap/interface/6716?utm_source=stack-comment).

**Review by JackShort — APPROVED** [review]

**Review by cbachmeier — DISMISSED** [review]
LGTM

**Review by tinaszheng — APPROVED** [review]

**Comment by just-toby** [comment]
@just-toby started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Uniswap/interface/6716).

**Comment by just-toby** [comment]
[Graphite](https://app.graphite.dev/github/pr/Uniswap/interface/6716) rebased this pull request as part of a merge.

**Comment by just-toby** [comment]
[Graphite](https://app.graphite.dev/github/pr/Uniswap/interface/6716) couldn't merge this PR because it was not satisfying all requirements.

**Review by JackShort — APPROVED** [review]

**Review by cbachmeier — APPROVED** [review]

**Pull request merged**
