### PR TITLE
feat: Enable queries for mixed routes 

### PR DESCRIPTION
**Pull request by zhongeric**
Adding `Protocol.MIXED` to the `protocols` array that is sent to the routing-api and clientSide smart order router.

Essentially a feature flag for the mixed routes launch

### CODE REVIEW

**Comment by vm** [comment]
I think this PR can just be `forceMixedRoutes: true` on the routing api config?

**Comment by zhongeric** [comment]
`forceMixedRoutes` should only be used for testing. That forces every single swap to use a mixed route. By including it in the protocols array, we give the router the option to select a mixed route if it's better than others.

**Comment by zzmp** [comment]
> This will fail until routing-api is deployed to prod because of query param change

does this mean that turning it off on the server will cause the client to crash?

**Comment by zhongeric** [comment]
> > This will fail until routing-api is deployed to prod because of query param change
> 
> does this mean that turning it off on the server will cause the client to crash?

Not anymore since we deployed new routing-api

**Comment by vm** [comment]
can you rebase against main instead of merging? or reset and just add the last commit you need, otherwise this commit log is confusing

**Review by zzmp — APPROVED** [review]

**Comment by vm** [comment]
Moved to new PR

**Pull request closed without merging**
