### PR TITLE
fix: userHideClosedPositions persist between browser refreshes

### LINKED ISSUE #2356: Fix "Show closed positions" checkbox state saving behaviour on Arbitrum to be consistent with mainnet
**Bug Description**
The state of the checkbox "Show closed positions" on the [positions overview page](https://app.uniswap.org/#/pool) saves the state of the checkbox on Arbitrum in an unexpected way which is inconsistent with behaviour of mainnet. On mainnet the state is saved for the user the moment the checkbox is interacted with. On Arbitrum the checkbox state seems to get saved only on page change.

**Steps to Reproduce**

1. Make sure you are a liquidity provider in any pool on UniswapV3 on Arbitrum and have at least one open and one closed position.
2. Go to https://app.uniswap.org/#/pool
3. Observe state of checkbox "Show closed position"
4. Change state of said checkbox
5. Refresh the page
6. Observe that state of checkbox got reset to state in Step 3
7. Change checkbox state again
8. This time don't refresh but click on "Swap" Menu item
9. Click on "Pool" Menu item to get back to the positions overview
10. Observe state of checkbox now is correctly set to the state set in Step 7.

**Expected Behavior**
I expect the state of the checkbox getting saved for the user the moment I change the state, not on leaving the page.

**Additional Context**
It may behave similar on Optimism, didn't test it.
Browser (latest as of writing this report): Brave Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by Jdecristi**
## Description
Fixes #2356 

## Screen capture

|    Before    |   After    |
| ------------ | ------------ |
| <video src="https://github.com/Uniswap/interface/assets/89173284/f492b74d-c299-4acd-b8bf-70631d1fc5ea" /> | <video src="https://github.com/Uniswap/interface/assets/89173284/3809049b-fa27-4a34-986f-455b96c90bda" /> 
 |

### Reproducing the error

1. navigate tp http://app.uniswap.org/pools
2. Click on "Show closed positions"
3. Refresh the page

### CODE REVIEW

**Review by zzmp — CHANGES_REQUESTED** [review]
Thanks for you contribution! Usually, we save state using either the redux or jotai atom abstractions. This is already stored in the redux state (through the user reducer). Are you sure it's not being saved through redux? If it's not, could you fix it through redux, instead of adding a one-off sessionStorage usage?

**Comment by Jdecristi** [comment]
@just-toby I noticed persist actions are being ignored due to redux migrations. Where should this be persisting from?

#### This is from "src/state/reducer.ts"
Screenshot 2023-09-15 at 6 01 57 PM

#### This is from "src/state/index.ts"
Screenshot 2023-09-15 at 6 02 16 PM

**Comment by just-toby** [comment]
hi @Jdecristi  thanks for the PR  - the `ignoredActions` here are specifically saying which actions to ignore during the serializable check. so those lines are not disabling persistence in any way, and as far as i can tell persistence is working correctly. 

when i test toggling `userHideClosedPositions`, i'm seeing the expected behavior. the change is being persisted to IndexedDB correctly.

are you sure that issue #2356 is related to persistence failing? it seems like it's describing different behavior across different chains. not to mention the issue is 2 years old, so i'm not sure it's relevant anymore.

**Review by just-toby — CHANGES_REQUESTED** [review]
i don't think this is needed

**Comment by Jdecristi** [comment]
> i don't think this is needed

I can't see the changes in the DB, and the data doesn't persist on either Chrome or Firefox for me

https://github.com/Uniswap/interface/assets/89173284/43e68a58-8442-4c65-a5ec-86f3fe54ed84

**Comment by just-toby** [comment]
@Jdecristi try clicking the refresh icon in the top left of that pane. indexed db data doesn't update in real time. there is a warning that the data is stale

**Comment by Jdecristi** [comment]
@just-toby Awesome! I got it now I'll go ahead and close the PR. Will you close the associated issue so no one tries to take it in the future?

**Pull request closed without merging**
