### PR TITLE
fix: use simple toggle instead of toggle with text init commit

### PR DESCRIPTION
**Pull request by lynnshaoyu**
Fix bug: https://github.com/Uniswap/interface/issues/1828

Simplify toggles and remove on/off text that doesn't look good when translated to other languages (due to differing text lengths). 

I also refactored and simplified the toggle code. Deleted ListToggle and SimpleToggle (from https://github.com/Uniswap/interface/pull/3858) to unify into one configurable toggle for all our needs. Simplified and removed unnecessary "isToggleOn" state in original implementation as well.

### CODE REVIEW

**Comment by lynnshaoyu** [comment]
Video image of toggles post fix:
https://user-images.githubusercontent.com/41491154/171948305-21c79261-1a27-4652-816f-93aca43cd268.mp4

Screenshots: 
Screen Shot 2022-06-03 at 4 35 08 PM
Screen Shot 2022-06-03 at 4 34 38 PM
Screen Shot 2022-06-03 at 4 34 32 PM

**Review by ianlapham — APPROVED** [review]
Looks good!

**Comment by infredible** [comment]
Looking good! One nitpick: could we add a transition animation? The current behavior looks a bit jarring without it. 

An ease-out, 100ms transition would be great.

https://user-images.githubusercontent.com/3887562/171957409-cca3fc59-c9e6-4ea2-a484-9be6aedf0d86.mp4

**Comment by lynnshaoyu** [comment]
Added 0.1 second ease-in animations!

https://user-images.githubusercontent.com/41491154/172074251-8284bcd3-db0b-4201-82db-ca30115817ce.mp4

**Comment by willhennessy** [comment]
thanks lynn this looks great!  one reallly tiny nit:  when the page first loads, the toggle slides over to the right position. This feels like a form of page thrash.  Is it possible to set an initial value for the toggle?

oddly sometimes the value is initial to off (show closed positions on the pool page), and sometimes to on (collect as WETH on the position page)

**Pull request merged**
