### PR TITLE
feat: render blurred collection cover photo in the header

### PR DESCRIPTION
**Pull request by grabbou**
Fixes WEB-2182
Fixes WEB-1276

Todo:
- [x] linear gradient when missing background
- [x] light mode
- [x] fix backdrop on card items
- [x] reduce number of hardcoded heights/widths for easier responsiveness (follow-up ticket)
- [x] fix text selection when tapping next/prev icons in carousel

### CODE REVIEW

**Comment by grabbou** [comment]
This is ready for review. There are still a few things to handle as a follow-up, such as better scaling on smaller devices, rounding up prices etc., but we're tracking that all separately on Jira.

**Comment by grabbou** [comment]
Screenshots of the interface uploaded to associated Jira task

**Comment by callil** [comment]
@grabbou There is one additional key value to make this work. Banner image should be adjusted to be `opacity: 0.4` in dark mode and `opacity: 0.2` in light mode

**Review by JackShort — APPROVED** [review]
non blocking comments over slack

**Comment by grabbou** [comment]
Thanks for the review! @JackShort let's follow up on Slack, if there's any further changes, we will send a next PR (there's a lot of work on this component up in front of me anyway).

@callil thank you for the help on reviewing this too!

**Pull request merged**
