### PR TITLE
fix: add crossplatform `prei18n-extract` script

### PR DESCRIPTION
**Pull request by brunocrosier**
Previous `prei18n-extract` script used `touch` which does not exist on Windows.

Implement `prei18n-extract.js`, which runs the correct command based on the platform

Logic for `isWindows` is borrowed from the popular `cross-env` package: https://github.com/kentcdodds/cross-env/blob/master/src/is-windows.js

Fixes https://github.com/Uniswap/interface/issues/2442

Screenshot of the command working on my Windows machine:

image

### CODE REVIEW

**Review by zzmp — CHANGES_REQUESTED** [review]
Can you simplify this (and avoid adding the helper file) by using a x-platform to like [shx](https://www.npmjs.com/package/shx)?

**Comment by brunocrosier** [comment]
> Can you simplify this (and avoid adding the helper file) by using a x-platform to like [shx](https://www.npmjs.com/package/shx)?

Good idea, updated accordingly!

**Review by zzmp — APPROVED** [review]

**Review by zzmp — CHANGES_REQUESTED** [review]
Sorry, but for security, we're not adding cross-platform-only packages to our dependencies (like `shx`).

**Comment by zzmp** [comment]
sorry to have gone back and forth on this

**Pull request merged**
