### PR TITLE
feat: upgrade @davatar/react to 1.6.0 for NFT ref support

### PR DESCRIPTION
**Pull request by carlosdp**
## Description

This PR updates the [@davatar/react](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react) package to 1.6.0, which adds the final bit of support for the ENS avatar spec: [avatars.md](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182).

Specifically, this new version adds support for the NFT reference spec for directly referencing NFTs in the avatar field. It only renders the avatar if the owner matches the address of the connected wallet.

## Security / Supply Chain risk consideration
The `@davatar/react` library uses minimal dependencies and is exact version matched. This new version adds no new dependencies from the previously pinned version.

## List of features added/changed

- Upgrade `@davatar/react` to 1.6.0
- Complete support for ENS avatar spec

## How Has This Been Tested?

Connected my wallet in the local dev environment and checked that it rendered my avatar correctly.

### CODE REVIEW

**Comment by NoahZinsmeister** [comment]
hey @carlosdp ! would love to use this PR as an opportunity to land https://github.com/TBDAO/davatar-helpers/pull/4 before merging

**Comment by carlosdp** [comment]
@NoahZinsmeister thanks for the PR! Updated this one to the new version that includes your optimization 💪

**Comment by carlosdp** [comment]
anything else needed on my end?

**Comment by zzmp** [comment]
This looks great, but it's a no-op. I didn't see it pending, and have already updated to 1.6.0 as part of #2415 to properly tree-shake @ethersproject from our bundle. Thanks for updating @davatar/react!

**Comment by carlosdp** [comment]
Oh cool, didn't notice. Thanks!

**Pull request closed without merging**
