### PR TITLE
fix: update polygon branding

### PR DESCRIPTION
**Pull request by LunrEclipse**
## Description

Updates Polygon's Logos and Branding as outlined by their [external branding kit](https://polygontechnology.notion.site/Polygon-Brand-Resources-External-2cd18ae436584e98a6c5aae56db73058). 

_Linear ticket:_ WEB-2647

### Before

Screenshot 2023-08-18 at 10 58 39 AM

Screenshot 2023-08-18 at 11 01 32 AM

Screenshot 2023-08-18 at 11 01 39 AM

### After

Screenshot 2023-08-18 at 10 58 55 AM

Screenshot 2023-08-18 at 11 00 48 AM

Screenshot 2023-08-18 at 11 01 07 AM

Screenshot 2023-08-18 at 11 09 56 AM

### Automated testing

- [x] Unit test N/A

### CODE REVIEW

**Review by cbachmeier — COMMENTED** [review]
Can you investigate why the new matic token logo has the black on sides and top? Looks like the purple is a square inside of a circle. Very noticeable on the details page in the top left https://interface-git-brendanwong-web-2647-update-polygo-b4d8b5-uniswap.vercel.app/tokens/polygon/NATIVE
New:
Screenshot 2023-08-18 at 9 27 19 AM
Old:
Screenshot 2023-08-18 at 9 27 24 AM

**Review by cbachmeier — APPROVED** [review]
LG overall just the one nit about the matic token logo being off

**Comment by LunrEclipse** [comment]
> LG overall just the one nit about the matic token logo being off

Yeye so I took a look at close up I think it's still circular, however, there is a gap between the icon and the border.

Screenshot 2023-08-18 at 1 24 17 PM

Screenshot 2023-08-18 at 1 31 08 PM

Which I think is caused by the fact that the new SVG isn't flush against the border like the old one was.

Screenshot 2023-08-18 at 1 29 53 PM

Should I ask someone on design to fix that or how do you think I should proceed?

**Comment by LunrEclipse** [comment]
> > LG overall just the one nit about the matic token logo being off
> 
> Yeye so I took a look at close up I think it's still circular, however, there is a gap between the icon and the border.
> 
> Screenshot 2023-08-18 at 1 24 17 PM Screenshot 2023-08-18 at 1 31 08 PM
> Which I think is caused by the fact that the new SVG isn't flush against the border like the old one was.
> 
> Screenshot 2023-08-18 at 1 29 53 PM
> Should I ask someone on design to fix that or how do you think I should proceed?

Ok, I had Maggie readjust the logo so it should be good now!

Screenshot 2023-08-18 at 2 03 32 PM

**Review by cbachmeier — APPROVED** [review]
thanks for fixing

**Review by zzmp — APPROVED** [review]

**Comment by gnewfield** [comment]
Rebased these changes on `main` in order to fix the failing cloud tests. Ready to merge.

**Review by cbachmeier — APPROVED** [review]

**Pull request merged**
