### PR TITLE
fix: Add ENSName and address check to Web3Status

### PR DESCRIPTION
**Pull request by uniyj**
Issue #2838

Note that I don't know TypeScript and frontend. In my tests (just printing `console.log`s), what I did here seems to work, but I have no idea if this is acceptable code or not... Someone should please review this. Thanks.

### CODE REVIEW

**Comment by uniyj** [comment]
@moodysalem, for Christmas I wrote a few lines of JS/TS =P
(Please check haha)

**Comment by tinaszheng** [comment]
Hey @uniyj, thanks for your contribution! We should probably be doing the equality check everywhere we use ENS name. Could you move that `useENSAddress` + equality check logic inside of `useENSName`?

**Comment by uniyj** [comment]
Hi @tinaszheng. That was what I wanted to do initially, but I am really not familiar with TS, React hooks, etc., and so did not want to mess with the hooks – in comparison, the Web3Status file seemed more straightforward to me...

In any case, I've now tried to move the ENSAddress check into ENSName hook, and reverted the previous changes to Web3Status. Again, no idea if it's acceptable code or not.

In my quick tests, it seems like a "stray" reverse-name will still show up momentarily before being replaced by the 0xXXX address again when the ENSAddress check kicks in. I have no idea why/how it does that, because I cannot actually decipher much of what's going on in TS and React hooks flows..!

**Comment by tinaszheng** [comment]
thanks @uniyj! your PR looks fine to me. can you explain more about what you mean by the "stray" reverse-name display? 

Are you seeing something like:
if 0xXX points to a.eth:

1) 0xXX address shows for a few seconds and then
2) a.eth shows? 

If so, that's fine. Are you seeing a different behavior?

**Comment by uniyj** [comment]
I haven't actually tried to set a reverse-ENS for my address to an ENS name that does not forward back to that address, so cannot fully test what happens there (see what's mentioned in comments in issue #2838).

I tried to somewhat replicate that behaviour by flipping the logic check to `const checkedName = address !== fwdAddr?.address ? name : null` and seeing what happens. What I observed in the status box was then:

1. Status shows `0xXXX` address
2. Eth balance loads in status
3. `0xXXX` changes to show the reverse-ENS set for that address (not sure why this happens first)
4. The flipped logic check seems to then trigger (mimicking that the ENS name does not forward to the address)
5. The ENS name changes back to show `0xXXX`

**Comment by tinaszheng** [comment]
That logic doesn't really replicate the behavior of having a different reverse proxy but that's ok. Given the logic that behavior seems expected and fine to me. The order of sequence for the states will be:

1. `address` is defined, `fwdAddr`, `name` are both undefined
2. `address` is defined, `name` is defined, `fwdAddr` is undefined
3. `address`, `name`, and `fwdAddr` are all defined

i added an inline comment just as a note to future developers, but otherwise this looks great to me~ thanks so much!

**Review by tinaszheng — APPROVED** [review]

**Pull request merged**
