### PR TITLE
style: ban esnext syntax

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
This could also be accomplished via browserslist compliance, with something like [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat).

**Comment by justindomingue** [comment]
why are we banning esnext?

**Comment by zzmp** [comment]
This was an attempt at browser compatibility, but we couldn't get the CI linter to accept it.

**Comment by sambacha** [comment]
> This could also be accomplished via browserslist compliance, with something like [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat).

would be interested to hear your thoughts on the subject of browserlist usage , see https://github.com/Uniswap/interface/pull/2140

**Pull request closed without merging**
