### PR TITLE
chore: update nft grays

### PR DESCRIPTION
**Pull request by vm**
Renames grey to gray.
Adds new variables.
Updates existing.

### CODE REVIEW

**Review by cbachmeier — CHANGES_REQUESTED** [review]
Still a couple places where `grey` colors are still used, especially in the light and dark theme files
Screen Shot 2022-11-08 at 11 47 48

**Comment by vm** [comment]
sorry yea pr wasn't finished yet need to do a find and replace

**Comment by vm** [comment]
Please view with `hide whitespace` enabled.

**Comment by cbachmeier** [comment]
Collection pages with graphql are crashing for me. Working on main

**Pull request merged**
