### PR TITLE
refactor: removes unused useFastForwardBlockNumber

### PR DESCRIPTION
**Pull request by enzoferey**
I was looking through the updater implementation and I noticed this hook is actually not being used.

### CODE REVIEW

**Comment by cmcewen** [comment]
thanks @enzoferey! looking at this i don't see us use fastForward anywhere, so could you remove it completely?

**Comment by enzoferey** [comment]
@cmcewen yes of course ! 👍🏻

**Comment by enzoferey** [comment]
@cmcewen done, let me done if that's not what you had in mind as a full clean up related to the `fastForward` block number feature 👍🏻

**Review by vm — APPROVED** [review]

**Comment by enzoferey** [comment]
Cheers 👍🏻

**Pull request merged**
